### ISSUE TITLE
"Donations" collection/publication would make more sense being called "Donation Claims"

### ISSUE THREAD

**Issue by LDubya** [For-Science/Crypto-For-Science#1]
The "Donations" collection is slightly misnamed, as it's really set up to store donation claims. To remove ambiguity (since "Donations" is very likely to be the name for the collection used to help calculate cryptocurrency donation totals for projects -- currently being done manually by spreadsheet), I think the collection should be renamed to DonationClaims.

This is really not that complex, just kind of time-consuming as it boils down to renaming a bunch of strings in different locations. Great way to make a contribution and become familiar with a large portion of the code base.

### rename folders:

/imports/api/donations/ -> /imports/api/donationClaims/

etc...

### rename variables:

- let "Donations" -> let "DonationClaims"
- Meteor.publish("donations.forProject" -> Meteor.publish("donationClaims.forProject"

etc...

### rename files: 

- donation-collection.js -> donationClaims-collection.js
- donation-methods.js -> donationClaim-methods.js 
- donation-publications.js -> donationClaim-publications.js

etc...

### refactor

- import { Donations } -> import { DonationClaims }
- this.subscribe("donations.forProject" -> this.subscribe("donationClaims.forProject"

etc...

### test

make sure it works by submitting a donation claim for a project and then logging in as the project owner and approving/rejecting that donation claim

---

Comment below if you plan to submit a pull request for this

**Comment by ctvanzandt42** [comment]
I'll take this issue on! Expect a pull request in the coming days.
