### ISSUE TITLE
New feature request: Update total funds received automatically

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [For-Science/Crypto-For-Science#10]
If anyone wants to take development of this feature, just assign yourself here.

Right now we're updating the totals received automatically every few hours. (Relevant Trello item: https://trello.com/c/AYBMXZyY/23-say-on-the-website-that-the-total-is-updated-every-few-hours)

Optimally, the website would monitor the BTC and ETH addresses of each researcher and add the equivalent in USD to total received (by using the BTC and ETH price averages for the last day, so that price spikes don't disturb the flow). It should also add on top of that the amount that he started with, plus the contributions that the researches added manually (which could be for example wire transfers received).

**Comment by wildaces215** [comment]
I would like to tackle this!

**Comment by Laurentiu-Andronache** [comment]
Thank you! Looking forward to your pull request.

If you want, you can also join our Slack through this link: https://join.slack.com/t/forseh/shared_invite/enQtMzQ5MzI1Mjc2NTMwLWZkMzRmNmM5NzRhNzM0OWE2MzlmNTZlMWJjYzViNmU0NjFmMjM3MTAyYzJiOWQ0NTVhMWZjMGNiYmJiMWI0NDg

Channel #developers

**Comment by wildaces215** [comment]
Thanks I'll start when I get a chance!

**Comment by LDubya** [comment]
in the latest commit. Updates every hour. 

Sample campaigns are connected to the test BTC and ETH addresses, which are very active, so those sample campaigns have received unheard amounts of money.

**Comment by LDubya** [comment]
July 10th. See comments above.
