### ISSUE TITLE
New feature request: Open graph meta tags

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [For-Science/Crypto-For-Science#12]
If anyone wants to take development of this feature, just assign yourself here.

In order for our pages to show up nicely when they're shared on social media, we need open graph integration.  For the main page, they should probably be set from the admin panel. For campaigns, they should be set automatically from campaign picture (dependent on https://github.com/For-Science/Crypto-For-Science/issues/8) + campaign title + campaign short description (optionally they could be editable from the account of the campaign submitter - not an essential extra feature).

**Comment by LDubya** [comment]
I'll assign this one to myself

**Comment by LDubya** [comment]
in 3b9e1e1 & e452109

Follows facebook's best practices: "target one of these user agents to serve the crawler a nonpublic version of your page that has only metadata and no actual content" - [Facebook Crawler - Sharing](https://developers.facebook.com/docs/sharing/webmasters/crawler)

routes

- /projects/:projectID
  - generated from project data
- /
  - hard-coded, based on home page description below. 
  - description:
    - "Crypto For Science is a crowdfunding platform that uses the spirit of cryptocurrency in order to fund scientific research: no fees and no intermediaries - all the funds go directly to the researchers"

Will close this when you can edit the description from admin

**Comment by LDubya** [comment]
987f6fa gives the admin a "CFS Meta" tab that they can use to edit the facebook meta description.
