### ISSUE TITLE
Project URLs need to be slugs instead of GUID

### ISSUE THREAD

**Issue by LDubya** [For-Science/Crypto-For-Science#13]
Currently the project URLs are meaningless GUID's.

It would be better if the project URLs contained slugs based on the project title, for SEO purposes, etc.

**Comment by LDubya** [comment]
- 7ddd933

Project urls use slugs. Better for SEO since the project title is in the URL.

route:  `/projects/p/:projectId/:slug`

in the future could probably make the urls a bit shorter by setting up an incrementing key, and using that instead of projectId

Note that this is a breaking change; if you're going to pull this or push anywhere, you'd need to either
- add slugs manually to the projects collection (for the current projects in your instance)
- or if you don't mind losing the project data you can either 
  - just clear out the project collection
  - or do a $meteor reset ( this will reset the entire database including users )

**Comment by Laurentiu-Andronache** [comment]
Reopening this because while URL's look better now, they still look bad overall. Maybe someone can come up with a solution...

**Comment by LDubya** [comment]
better slugs in latest commit
