### ISSUE TITLE
Fix needed: new rows in the description shouldn't disappear

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [For-Science/Crypto-For-Science#15]
If anyone wants to take development of this fix, just assign yourself here.

It would be great if we had RTF descriptions. Or at least fix so that we can have new rows in them. Without them, formatting is difficult because this is how I write the text:

![image](https://user-images.githubusercontent.com/16560332/39752810-7aba40d0-52b4-11e8-9a40-34e65e447211.png)

And this is how it shows up (go to Description):
https://cryptoforscience.com/projects/p/ySxWpWEmBC2Ef38wo/test-funding-request-for-scientific-research#title

**Comment by LDubya** [comment]
in c1663ae

**Comment by LDubya** [comment]
Fixed May 13
