### ISSUE TITLE
New feature request: TOS for project submitters, where they have to agree with funds recycling

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [For-Science/Crypto-For-Science#7]
If anyone wants to take development of this feature, just assign yourself here.

From our README:

> An interesting feature will be funds recycling: if someone doesn't get funded at the soft cap in the time chosen by him (translated: with the minimum funds that he needs), it's his own responsibility to choose other projects from the website, and donate everything that he's received until then to them. Afterwards, he's allowed to restart the campaign while disclosing that this has happened in the description. Similarly, if he receives more money (for example because some cryptocurrency that he received went up a lot in value)... it's his own responsibility to donate the surplus to other projects.

Before someone is allowed to submit a project, he must agree with a simple TOS that tells him how funds recycling works. This TOS must be editable from the Admin interface.

Relevant Trello items:

https://trello.com/c/FEQP8NHE/3-recycling-of-unmet-soft-caps

https://trello.com/c/zxh01uQ5/21-dealing-with-projects-whose-funding-period-have-ended

https://trello.com/c/v81kesI4/24-dealing-with-surpassed-goals

**Comment by LDubya** [comment]
e811972 adds the condition to the project submission form, similar to what CloudFlare does: https://www.cloudflare.com/a/sign-up

**Comment by LDubya** [comment]
May 13th
