### ISSUE TITLE
New feature request: Mandatory project photos with the researcher or the team requesting funding

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [For-Science/Crypto-For-Science#8]
If anyone wants to take development of this feature, just assign yourself here.

Feature is described here:
https://trello.com/c/WBfA1dG1/5-project-photo

Please don't also show the photos on the main page, because I'll end up paying more for bandwidth.

**Comment by LDubya** [comment]
Did some prelim work on this today, will have a v1 for this feature soon

**Comment by LDubya** [comment]
b4f877a

- user is instructed to upload image for their project 
- images shown on admin page for project under "my campaigns"
- image shown on public project page
- project image is included with the open graph meta tags for the project route

**Comment by LDubya** [comment]
in production. All new projects require images.

**Comment by Laurentiu-Andronache** [comment]
What's the ETA on this one?

**Comment by LDubya** [comment]
This should be working as of 4 days ago. All new projects require images. It's just that the demo projects don't have images and that's all we have by default.
